dist: xenial
language: python
python:
  - "3.8"
  - "3.8-dev"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pipenv run black --check .
  - pipenv run isort --check-only
  - pipenv run pydocstyle
  - find . -iname "*.py" | xargs pipenv run pylint
  - pipenv run coverage run --source=unixtimestamp --append --module pytest
  - pipenv run coverage run --source=unixtimestamp --append --module behave
  - pipenv run coverage xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email:
    on_success: never
    on_failure: always
