version: 2
jobs:
  build:
    working_directory: ~/unixtimesta.mp
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y locales-all npm
            pip install --requirement requirements.txt
            npm install

      - run:
          name: run tests
          command: pytest

      - run:
          name: run BDD tests
          command: behave

      - run:
          name: check code formatting
          command: |
            black --check --diff .
            isort --check-only .
            find . -iname "*.py" | xargs pylint
            npx prettier --check -- **/*.html 
            npx prettier --check -- **/*.scss

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
